version: '3.8'

services:
  api:
    build: .
    container_name: manager_api_prod
    ports:
      - "8000:8000"
    # No escribimos las variables aquí. 
    # Dokploy las inyectará desde su panel de "Environment Variables".
    
    deploy:
      resources:
        limits:
          cpus: '0.80'          # Límite máximo (techo)
          memory: 1280M        # 1GB de RAM máximo
        reservations:
          cpus: '0.25'          # Reserva garantizada (piso)
          memory: 1024M

    restart: always
    networks:
      - red_infraestructura

networks:
  red_infraestructura:

    external: true

